[package]
name = "rafter"
version = "0.1.0"
authors = ["gareth <gareth.charnock@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"

[dev-dependencies]
env_logger = "0.7.1"
lazy_static = "1.4.0"
